server: 
  port: 8088
    
spring:
  datasource:
    driverClassName: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@172.30.3.74:1521/masterpdb
    username: fplatform
    password: 123456
    test-on-borrow: true
    testWhileIdle: true
    validation-query: SELECT 1
    max-idle: 10
    max-wait: 10000
    min-idle: 5
    initial-size: 5
    test-while-idle: true
    time-between-eviction-runs-millis: 18800
    jdbc-interceptors: ConnectionState;SlowQueryReport(threshold=0)
    
    
    
    
  redis:  
    database: 0
    host: 127.0.0.1  
    port: 6379
    pool: 
      max-idle: 8
      min-idle: 0
      max-active: 8
      max-wait: -1
    
mybatis:
  mapper-locations: classpath*:/mapper/*.xml